#define CAN_MINE(ch)    ( ROOM_FLAGGED(IN_ROOM(ch), ROOM_GOLD_DEPOSIT) || \
                          ROOM_FLAGGED(IN_ROOM(ch), ROOM_SILVER_DEPOSIT) || \
                          ROOM_FLAGGED(IN_ROOM(ch), ROOM_COPPER_DEPOSIT) || \
                          ROOM_FLAGGED(IN_ROOM(ch), ROOM_IRON_DEPOSIT) || \
                          ROOM_FLAGGED(IN_ROOM(ch), ROOM_ANTIMONY_DEPOSIT) || \
                          ROOM_FLAGGED(IN_ROOM(ch), ROOM_CHROMIUM_DEPOSIT) || \
                          ROOM_FLAGGED(IN_ROOM(ch), ROOM_TIN_DEPOSIT) || \
                          ROOM_FLAGGED(IN_ROOM(ch), ROOM_PLASTONIUM_DEPOSIT))

#define CAN_MINE_GOLD(ch) 	ROOM_FLAGGED(IN_ROOM(ch), ROOM_GOLD_DEPOSIT)
#define CAN_MINE_SILVER(ch) 	ROOM_FLAGGED(IN_ROOM(ch), ROOM_SILVER_DEPOSIT)
#define CAN_MINE_COPPER(ch)	ROOM_FLAGGED(IN_ROOM(ch), ROOM_COPPER_DEPOSIT)
#define CAN_MINE_IRON(ch)	ROOM_FLAGGED(IN_ROOM(ch), ROOM_IRON_DEPOSIT)
#define CAN_MINE_ANTIMONY(ch)	ROOM_FLAGGED(IN_ROOM(ch), ROOM_ANTIMONY_DEPOSIT)
#define CAN_MINE_CHROMIUM(ch)	ROOM_FLAGGED(IN_ROOM(ch), ROOM_CHROMIUM_DEPOSIT)
#define CAN_MINE_TIN(ch)      ROOM_FLAGGED(IN_ROOM(ch), ROOM_TIN_DEPOSIT)
#define CAN_MINE_PLASTONIUM(ch) ROOM_FLAGGED(IN_ROOM(ch), ROOM_PLASTONIUM_DEPOSIT)

#define GET_MOB_PREG(ch)	ch->mob_specials.pregnant
