
/* these are subskills  - mord*/
enum subskill_list {
SUB_UNDEFINED, //0
SUB_FURY_ATTACKS,
SUB_NIGHT_REGEN,
SUB_DRAIN_BLOOD,
SUB_PILLAGE,
SUB_REFINE_ORE,
SUB_REFINE_GEMS,
SUB_REPROCESS_ORE,
SUB_REPROCESS_GEMS,
SUB_INDUSTRY,
SUB_MARKETING,//10
SUB_BARTER,
SUB_SOFT_MINING,
SUB_HARD_MINING,
SUB_SHARPENING,
SUB_LEATHERWORK,
SUB_TAILORING,
SUB_SURVEYING,
SUB_ELECTRONICS,
SUB_SMALL_SHIELDS,
SUB_LARGE_SHIELDS,//20
SUB_DECYPHERING,
SUB_HEAVY_WEAPONS,
SUB_LIGHT_WEAPONS,
SUB_BREWING,
SUB_SUPERVISING,
SUB_MANAGEMENT,
SUB_LEADERSHIP,
SUB_GROUP_COORDINATION,
SUB_HEAVY_ARMOR,
SUB_MEDIUM_ARMOR,//30
SUB_LIGHT_ARMOR,
SUB_LIGHTSABER_PROF,
SUB_LIGHTSABER_DOUBLE,
SUB_DOGFIGHTING,
SUB_COCKFIGHTING,
SUB_STREETFIGHTING,
SUB_DEVINE_WATER,
SUB_CREATE_WELL,
SUB_OPTICS,
SUB_MILLING,//40
SUB_PAPERMAKING,
SUB_SCROLLMAKING,
SUB_HEAT_MANAGEMENT,
SUB_GLASSWORK,
SUB_BOTTLEMAKING,
SUB_VIALMAKING,
SUB_LUMBERJACK,
SUB_TREEGUARD,
SUB_LOYALSPEED,
SUB_LOYALATTACK,//50
SUB_LOYALDEFEND,
SUB_LOYALDAMAGE,
SUB_LYCAN,
SUB_STUN_PHASER,
SUB_JUGGLE,
SUB_GAROTTE,
SUB_DRAGON_SUMMONING,
SUB_DRAGON_TAMING,
SUB_DRAGON_ENCHANTING,
SUB_DRAGON_MOUNTING,//60
SUB_DRAGON_MASTERY,
SUB_DRAGON_FLYING,
SUB_DRAGON_CARGO,
SUB_DRAGON_PASSENGERS,//64
SUB_BEASTTAME,
SUB_BEASTTONGUE,
SUB_BEASTMASTER,
SUB_TASKMASTER,
SUB_UNDEAD_OVERLORD,
SUB_UNDEAD_DEMON, //70
SUB_UNDEAD_MINORDEMON,
SUB_UNDEAD_DRAGON,
SUB_UNDEAD_MASTER,
SUB_UNDEAD_SUMMON,
SUB_UNDEAD_WORSHIP,//75
SUB_TRIP,
SUB_THROTTLE,
SUB_MASK,
SUB_CLOAK,
SUB_SHADOWCLOAK,
SUB_BALANCE,
SUB_TUMBLE,
SUB_CLOWN,
SUB_TRAPEZE,
SUB_CHARCOALBURNER,
SUB_BRICKMAKING,
SUB_TUNNELING,
SUB_REPEL_SANC,
SUB_UNDYING,
SUB_SWEEP_ATTACK,
TOP_SUB_DEFINE
};

enum sub_status_types {
STATUS_TYPE_TRAINABLE,
STATUS_TYPE_ONOFF
};

enum sub_professions_list {
PROF_MISC,
PROF_NECROMANCER,
PROF_DRAGONMASTER,
PROF_PERFORMER,
PROF_WOODSMAN,
PROF_BEASTMASTER,
PROF_GLAZIER,
PROF_SCRIBE,
PROF_BUSINESS,
PROF_COMMERCE,
PROF_MINER,
PROF_VAMPIRE,
PROF_BREWER,
PROF_COMBATANT,
PROF_TANNER,
PROF_MILLER,
PROF_WEAVER,
PROF_BLACKSMITH,
PROF_TAILOR,
PROF_TECH,
PROF_MANAGEMENT,
PROF_PILOT,
//--
PROF_FARRIER,
PROF_GOLDSMITH,
PROF_METALLURGIST,
PROF_WEAPONSMITH,
PROF_FURRIER,
PROF_SHOEMAKER,
PROF_GLOVEMAKER,
PROF_ARMOURER,
PROF_CARDER,
PROF_SPINNER,
PROF_DRESSMAKER,
PROF_CARPENTER,
PROF_CABINETMAKER,
PROF_SHIPBUILDER,
PROF_QUARRIER,
PROF_COLLIER,
PROF_BRICKMAKER,
PROF_MASON,
PROF_MIRRORMAKER,
PROF_CONTRACTOR,
PROF_PALADIN,

PROF_MAX
};

enum prof_group_list {
PGRP_MISC,
PGRP_METALWORKER,
PGRP_LEATHERWORKER,
PGRP_TEXTILEWORKER,
PGRP_WOODWORKER,
PGRP_STONEWORKER,

PGRP_MAX
};

enum sub_status_toggle {
STATUS_OFF,
STATUS_ON
};

struct sub_list {
enum subskill_list subskill;
int learn;
enum sub_status_types status;
struct sub_list *next;
};



#define SUB_TYPE_TEACHABLE 	(1 << 0)
#define SUB_TYPE_EXP 		(1 << 1)
#define SUB_TYPE_CMD		(1 << 2)
#define SUB_TYPE_AUTO 		(1 << 3)
#define SUB_TYPE_DEFAULT_ON     (1 << 4)
#define SUB_TYPE_PROF		(1 << 5)

extern struct sub_skill_info_type sub_info[];


